name: compose issue

on:
  pull_request:
    branches:
      - "main"

jobs:
  test_suite:
    runs-on: ubuntu-latest  # [self-hosted, generic-runner]

    steps:
        - name: Checkout
          uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
            
        - name: Switch to Current Branch
          run: git checkout ${{ env.BRANCH }}

        - name: Show current pwd
          run: pwd

        - name: Expanded relative in build ✔️ 
          run: docker compose -f app/docker-compose.yaml -f wrapper/compose.yaml --profile dev config --format json | jq -r .services.app.build.context

        - name: CUSTOM build ✔️ 
          run: CUSTOM_CONTEXT=/tmp docker compose -f app/docker-compose.yaml -f wrapper/compose.yaml --profile dev config --format json | jq -r .services.app.build.context

